<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>.lua</string>
	</array>
	<key>name</key>
	<string>Lua (Summit)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.lua</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lua.summit</string>
	<key>uuid</key>
	<string>03796283-69ec-4128-8693-522451595db4</string>
</dict>
</plist>
