<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>.lua</string>
	</array>
	<key>name</key>
	<string>Lua (Summit)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.lua</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#summit-time</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#summit-http</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#summit-soap</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#summit-sms</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#summit-prefs</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#summit-channel</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#summit-channel-data</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>summit-channel</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(channel\.(say|play|gather|hangup|answer|dial))\b(?=[( {])</string>
			<key>name</key>
			<string>support.function.library.lua.summit.channel</string>
		</dict>
		<key>summit-channel-data</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(channel\.(data\.(domain|dnis|ani|direction|localnumber|remotenumber|destination|id)))\b</string>
			<key>name</key>
			<string>support.function.library.lua.summit.channel.data</string>
		</dict>
		<key>summit-http</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(http\.(get|post))\b(?=[( {])</string>
			<key>name</key>
			<string>support.function.library.lua.summit</string>
		</dict>
		<key>summit-prefs</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(prefs\.+)\b</string>
			<key>name</key>
			<string>support.function.library.lua.summit.util</string>
		</dict>
		<key>summit-sms</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(sms\.(send))\b(?=[( {])</string>
			<key>name</key>
			<string>support.function.library.lua.summit.util</string>
		</dict>
		<key>summit-soap</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(soap\.(soapCall))\b(?=[( {])</string>
			<key>name</key>
			<string>support.function.library.lua.summit</string>
		</dict>
		<key>summit-time</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(time\.(now|is_workday|is_business_hours|format|weekday_name|create|to_unix_ts|MONDAY|TUESDAY|WEDNESDAY|THURSDAY|FRIDAY|SATURDAY|SUNDAY|TIME_FORMAT|DATE_FORMAT|DEFAULT_INPUT_FORMAT))\b(?=[( {])</string>
			<key>name</key>
			<string>support.function.library.lua.summit.time</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lua.summit</string>
	<key>uuid</key>
	<string>03796283-69ec-4128-8693-522451595db4</string>
</dict>
</plist>
