<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>.lua</string>
	</array>
	<key>name</key>
	<string>Lua (Summit)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.lua</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#summit-util-time</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#summit-util-http</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#summit-util-soap</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#summit-util-sms</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#summit-channel</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>summit-channel</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(channel\.(say|play|gather|hangup|answer))\b(?=[( {])</string>
			<key>name</key>
			<string>support.function.library.lua.summit.channel</string>
		</dict>
		<key>summit-util-http</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(util\.(http\.(get|post)))\b(?=[( {])</string>
			<key>name</key>
			<string>support.function.library.lua.summit.util</string>
		</dict>
		<key>summit-util-sms</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(util\.(sms\.(send)))\b(?=[( {])</string>
			<key>name</key>
			<string>support.function.library.lua.summit.util</string>
		</dict>
		<key>summit-util-soap</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(util\.(soap\.(soapCall)))\b(?=[( {])</string>
			<key>name</key>
			<string>support.function.library.lua.summit.util</string>
		</dict>
		<key>summit-util-time</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(util\.(time\.(time_of_day|is_workday|is_business_hours|format|weekday_name|create|MONDAY|TUESDAY|WEDNESDAY|THURSDAY|FRIDAY|SATURDAY|SUNDAY|TIME_FORMAT|DATE_FORMAT|DEFAULT_INPUT_FORMAT)))\b(?=[( {])</string>
			<key>name</key>
			<string>support.function.library.lua.summit.util</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lua.summit</string>
	<key>uuid</key>
	<string>03796283-69ec-4128-8693-522451595db4</string>
</dict>
</plist>
